version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolar_cotacao
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306


## docker-compose exec mysql bash
## mysql -uroot -p dolar_cotacao
## CREATE TABLE cotacao (id VARCHAR(255), code VARCHAR(10), codein VARCHAR(10), name VARCHAR(100), high VARCHAR(20), low VARCHAR(20), bid VARCHAR(20), timestamp VARCHAR(20), create_date VARCHAR(50), PRIMARY KEY (id));